# Generated by Django 5.2.4 on 2025-07-24 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('especialidad', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoIdentificacion', models.CharField(max_length=50)),
                ('numeroIdentificacion', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoServicio', models.CharField(max_length=50)),
                ('añofiscal', models.IntegerField()),
                ('fechaSolicitud', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('finalizada', 'Finalizada'), ('asistente_asignado', 'Asistente Asignado'), ('Pendiente', 'Pendiente'), ('en_proceso', 'En proceso')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaraciones.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Declaracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeclaracion', models.CharField(max_length=50)),
                ('añofiscal', models.IntegerField()),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('egresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('enviada', 'Enviada'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('valorImpuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fechaPresentacion', models.DateField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaraciones.solicitudservicio')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateField(auto_now_add=True)),
                ('usuarioAsignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaraciones.asistentecontable')),
                ('solicitudServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaraciones.solicitudservicio')),
            ],
        ),
    ]
